"use server";
import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getDb } from "@/db";
import { auditLogs, companies } from "@/db/schema";
import { requireCompanyOperator } from "@/lib/company-operator";
export type CompanyActionState = { status: "idle" | "success" | "error"; message?: string };
const schema = z.object({ companyId: z.uuid(), name: z.string().trim().min(2).max(160), timezone: z.string().trim().min(3).max(80), currency: z.string().trim().length(3).transform((value) => value.toUpperCase()) });
export async function updateCompanyAction(_state: CompanyActionState, formData: FormData): Promise<CompanyActionState> { try { const parsed = schema.safeParse({ companyId: formData.get("companyId"), name: formData.get("name"), timezone: formData.get("timezone"), currency: formData.get("currency") }); if (!parsed.success) return { status: "error", message: "Revisa los datos de la empresa" }; try { new Intl.DateTimeFormat("es-MX", { timeZone: parsed.data.timezone }).format(); } catch { return { status: "error", message: "La zona horaria no es válida" }; } try { new Intl.NumberFormat("es-MX", { style: "currency", currency: parsed.data.currency }).format(0); } catch { return { status: "error", message: "La moneda no es válida" }; } const operator = await requireCompanyOperator(parsed.data.companyId); if (!operator.isPlatformAdmin && !["owner", "admin"].includes(operator.role ?? "")) return { status: "error", message: "Solo propietarios y administradores pueden cambiar esta configuración" }; const db = getDb(); await db.batch([db.update(companies).set({ name: parsed.data.name, timezone: parsed.data.timezone, currency: parsed.data.currency, updatedAt: new Date() }).where(eq(companies.id, parsed.data.companyId)), db.insert(auditLogs).values({ companyId: parsed.data.companyId, actorUserId: operator.appUserId, action: "company.settings.updated", entityType: "company", entityId: parsed.data.companyId, metadata: { name: parsed.data.name, timezone: parsed.data.timezone, currency: parsed.data.currency } })]); revalidatePath("/app", "layout"); revalidatePath("/app/admin", "layout"); return { status: "success", message: "Configuración actualizada" }; } catch (error) { console.error("[company:settings] failed", { error: String(error) }); return { status: "error", message: "No fue posible actualizar la empresa" }; } }
