import Link from "next/link";
import { asc, eq } from "drizzle-orm";
import { ChevronRight, MapPin } from "lucide-react";
import { BranchForm } from "@/components/branch-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getDb } from "@/db";
import { branches, companies } from "@/db/schema";
export async function BranchDirectory({ companyId, detailBasePath, canManage, showCompany, defaultTimezone }: { companyId?: string; detailBasePath: string; canManage: boolean; showCompany: boolean; defaultTimezone?: string }) { const db = getDb(); const [rows, companyRows] = await Promise.all([db.select({ id: branches.id, name: branches.name, status: branches.status, timezone: branches.timezone, address: branches.address, phone: branches.phone, companyId: companies.id, companyName: companies.name }).from(branches).innerJoin(companies, eq(companies.id, branches.companyId)).where(companyId ? eq(branches.companyId, companyId) : undefined).orderBy(asc(companies.name), asc(branches.name)), companyId ? Promise.resolve([]) : db.select({ id: companies.id, name: companies.name }).from(companies).where(eq(companies.status, "active")).orderBy(asc(companies.name))]); return <div className={canManage ? "grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_390px]" : undefined}><Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Sucursal</TableHead>{showCompany ? <TableHead>Empresa</TableHead> : null}<TableHead>Ubicación</TableHead><TableHead>Zona horaria</TableHead><TableHead>Estado</TableHead><TableHead className="w-16" /></TableRow></TableHeader><TableBody>{rows.map((branch) => <TableRow key={branch.id}><TableCell><div className="flex items-center gap-2"><MapPin className="size-4 text-violet-600" /><div><p className="font-medium">{branch.name}</p><p className="text-xs text-muted-foreground">{branch.phone ?? "Sin teléfono"}</p></div></div></TableCell>{showCompany ? <TableCell>{branch.companyName}</TableCell> : null}<TableCell className="max-w-64 truncate">{branch.address ?? "Sin dirección"}</TableCell><TableCell>{branch.timezone ?? "Heredada"}</TableCell><TableCell><Badge variant={branch.status === "active" ? "secondary" : "outline"}>{branch.status === "active" ? "Activa" : "Inactiva"}</Badge></TableCell><TableCell><Button variant="ghost" size="icon-sm" asChild><Link href={`${detailBasePath}/${branch.id}`} aria-label={`Administrar ${branch.name}`}><ChevronRight /></Link></Button></TableCell></TableRow>)}{!rows.length ? <TableRow><TableCell colSpan={showCompany ? 6 : 5} className="h-28 text-center text-muted-foreground">Aún no hay sucursales.</TableCell></TableRow> : null}</TableBody></Table></CardContent></Card>{canManage ? <BranchForm companies={companyRows} fixedCompanyId={companyId} defaultTimezone={defaultTimezone} /> : null}</div>; }
