"use client";
import { useActionState } from "react";
import { useFormStatus } from "react-dom";
import { Building2, LoaderCircle } from "lucide-react";
import { saveBranchAction, type BranchActionState } from "@/app/app/branch-actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
const initialState: BranchActionState = { status: "idle" };
function Submit({ editing }: { editing: boolean }) { const { pending } = useFormStatus(); return <Button type="submit" disabled={pending} className="w-full bg-violet-600 hover:bg-violet-700">{pending ? <LoaderCircle className="animate-spin" /> : <Building2 />}{editing ? "Guardar cambios" : "Crear sucursal"}</Button>; }
export function BranchForm({ companies, fixedCompanyId, branch, defaultTimezone = "America/Hermosillo" }: { companies: { id: string; name: string }[]; fixedCompanyId?: string; defaultTimezone?: string; branch?: { id: string; companyId: string; name: string; timezone: string | null; address: string | null; phone: string | null; email: string | null; status: "active" | "inactive" } }) { const [state, action] = useActionState(saveBranchAction, initialState); return <Card><CardHeader><CardTitle>{branch ? "Datos de la sucursal" : "Nueva sucursal"}</CardTitle><CardDescription>Ubicación, contacto y configuración regional.</CardDescription></CardHeader><CardContent><form action={action} className="space-y-4"><input type="hidden" name="branchId" value={branch?.id ?? ""} />{fixedCompanyId ? <input type="hidden" name="companyId" value={fixedCompanyId} /> : <div className="space-y-2"><Label htmlFor="branchCompany">Empresa</Label><select id="branchCompany" name="companyId" required defaultValue={branch?.companyId ?? ""} className="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="" disabled>Seleccionar empresa</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></div>}<div className="space-y-2"><Label htmlFor="branchName">Nombre</Label><Input id="branchName" name="name" defaultValue={branch?.name} required maxLength={160} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="branchPhone">Teléfono</Label><Input id="branchPhone" name="phone" type="tel" defaultValue={branch?.phone ?? ""} /></div><div className="space-y-2"><Label htmlFor="branchEmail">Correo</Label><Input id="branchEmail" name="email" type="email" defaultValue={branch?.email ?? ""} /></div></div><div className="space-y-2"><Label htmlFor="branchAddress">Dirección</Label><Textarea id="branchAddress" name="address" defaultValue={branch?.address ?? ""} rows={3} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="branchTimezone">Zona horaria</Label><Input id="branchTimezone" name="timezone" defaultValue={branch?.timezone ?? defaultTimezone} required /></div><div className="space-y-2"><Label htmlFor="branchStatus">Estado</Label><select id="branchStatus" name="status" defaultValue={branch?.status ?? "active"} className="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="active">Activa</option><option value="inactive">Inactiva</option></select></div></div>{state.status !== "idle" ? <p role="status" className={state.status === "success" ? "rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-800" : "rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700"}>{state.message}</p> : null}<Submit editing={Boolean(branch)} /></form></CardContent></Card>; }
