"use client";

import { useActionState } from "react";
import { ArrowDownToLine, ArrowUpFromLine, Banknote, LockKeyhole, UnlockKeyhole } from "lucide-react";

import { addCashMovementAction, closeCashSessionAction, openCashSessionAction, type FinanceActionState } from "@/app/app/cash-actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import type { getCashData } from "@/lib/commerce-data";

type Data = Awaited<ReturnType<typeof getCashData>>;
const initial: FinanceActionState = { status: "idle" };
const labels = { sale: "Venta", income: "Ingreso", withdrawal: "Retiro", refund: "Devolución", adjustment: "Ajuste" } as const;
const methods = { cash: "Efectivo", card: "Tarjeta", transfer: "Transferencia", giftcard: "Gift card" } as const;

export function CashDashboard({ companyId, currency, data }: { companyId: string; currency: string; data: Data }) {
  const [openState, openAction, opening] = useActionState(openCashSessionAction, initial);
  const [movementState, movementAction, moving] = useActionState(addCashMovementAction, initial);
  const [closeState, closeAction, closing] = useActionState(closeCashSessionAction, initial);
  const openSessions = data.sessions.filter((session) => session.status === "open");
  const money = (cents: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency }).format(cents / 100);
  const sessionTotals = (sessionId: string) => data.movements.filter((row) => row.sessionId === sessionId).reduce((totals, row) => { const direction = ["withdrawal", "refund"].includes(row.type) ? -1 : 1; totals[row.method] += row.amountCents * direction; return totals; }, { cash: 0, card: 0, transfer: 0, giftcard: 0 });
  return <div className="space-y-6">
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><UnlockKeyhole className="size-5" />Abrir caja</CardTitle><CardDescription>Solo puede existir una caja abierta por sucursal.</CardDescription></CardHeader><CardContent><form action={openAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="companyId" value={companyId} /><div className="space-y-2"><Label htmlFor="cashBranch">Sucursal</Label><select id="cashBranch" name="branchId" required className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="">Selecciona</option>{data.branches.filter((branch) => !openSessions.some((session) => session.branchId === branch.id)).map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></div><div className="space-y-2"><Label htmlFor="openingBalance">Fondo inicial</Label><Input id="openingBalance" name="openingBalance" type="number" min="0" step="0.01" defaultValue="0" required /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="openingNotes">Notas</Label><Textarea id="openingNotes" name="notes" maxLength={1000} /></div><ActionMessage state={openState} /><Button disabled={opening} className="sm:col-span-2">{opening ? "Abriendo…" : "Abrir caja"}</Button></form></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Banknote className="size-5" />Movimiento manual</CardTitle><CardDescription>Registra ingresos, retiros o ajustes con motivo obligatorio.</CardDescription></CardHeader><CardContent><form action={movementAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="companyId" value={companyId} /><div className="space-y-2"><Label>Sesión</Label><select name="sessionId" required className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="">Selecciona</option>{openSessions.map((session) => <option key={session.id} value={session.id}>{session.branchName}</option>)}</select></div><div className="space-y-2"><Label>Tipo</Label><select name="type" required className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="income">Ingreso</option><option value="withdrawal">Retiro</option><option value="adjustment">Ajuste positivo</option></select></div><div className="space-y-2"><Label>Método</Label><select name="method" required className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option></select></div><div className="space-y-2"><Label>Importe</Label><Input name="amount" type="number" min="0.01" step="0.01" required /></div><div className="space-y-2"><Label>Categoría</Label><Input name="category" required maxLength={100} placeholder="Ej. Papelería" /></div><div className="space-y-2"><Label>Motivo</Label><Input name="reason" required minLength={3} maxLength={1000} /></div><ActionMessage state={movementState} /><Button disabled={moving} className="sm:col-span-2">{moving ? "Registrando…" : "Registrar movimiento"}</Button></form></CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-2">{openSessions.map((session) => { const totals = sessionTotals(session.id); const expected = session.openingBalanceCents + totals.cash; return <Card key={session.id}><CardHeader><div className="flex items-start justify-between"><div><CardTitle>{session.branchName}</CardTitle><CardDescription>Abierta {new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "short" }).format(session.openedAt)}</CardDescription></div><Badge>Abierta</Badge></div></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3 text-sm"><Metric label="Fondo inicial" value={money(session.openingBalanceCents)} /><Metric label="Efectivo esperado" value={money(expected)} /><Metric label="Tarjeta neta" value={money(totals.card)} /><Metric label="Transferencia neta" value={money(totals.transfer)} /><Metric label="Gift cards" value={money(totals.giftcard)} /></div><form action={closeAction} className="space-y-3 border-t pt-4"><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="sessionId" value={session.id} /><Label htmlFor={`counted-${session.id}`}>Efectivo contado</Label><Input id={`counted-${session.id}`} name="countedCash" type="number" min="0" step="0.01" required /><Textarea name="notes" placeholder="Notas del corte" maxLength={1000} /><ActionMessage state={closeState} /><Button variant="destructive" disabled={closing}><LockKeyhole />{closing ? "Cerrando…" : "Cerrar caja"}</Button></form></CardContent></Card>; })}{openSessions.length === 0 ? <Card className="xl:col-span-2"><CardContent className="py-12 text-center text-muted-foreground">No hay cajas abiertas.</CardContent></Card> : null}</div>
    <Card><CardHeader><CardTitle>Historial de sesiones</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Sucursal</TableHead><TableHead>Apertura</TableHead><TableHead>Cierre</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Esperado</TableHead><TableHead className="text-right">Contado</TableHead><TableHead className="text-right">Diferencia</TableHead></TableRow></TableHeader><TableBody>{data.sessions.map((session) => <TableRow key={session.id}><TableCell className="font-medium">{session.branchName}</TableCell><TableCell>{new Intl.DateTimeFormat("es-MX", { dateStyle: "short", timeStyle: "short" }).format(session.openedAt)}</TableCell><TableCell>{session.closedAt ? new Intl.DateTimeFormat("es-MX", { dateStyle: "short", timeStyle: "short" }).format(session.closedAt) : "—"}</TableCell><TableCell><Badge variant={session.status === "open" ? "secondary" : "outline"}>{session.status === "open" ? "Abierta" : "Cerrada"}</Badge></TableCell><TableCell className="text-right">{session.expectedCashCents == null ? "—" : money(session.expectedCashCents)}</TableCell><TableCell className="text-right">{session.countedCashCents == null ? "—" : money(session.countedCashCents)}</TableCell><TableCell className="text-right">{session.differenceCents == null ? "—" : money(session.differenceCents)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Card><CardHeader><CardTitle>Movimientos recientes</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Tipo</TableHead><TableHead>Método</TableHead><TableHead>Motivo</TableHead><TableHead className="text-right">Importe</TableHead></TableRow></TableHeader><TableBody>{data.movements.slice(0, 200).map((row) => <TableRow key={row.id}><TableCell>{new Intl.DateTimeFormat("es-MX", { dateStyle: "short", timeStyle: "short" }).format(row.occurredAt)}</TableCell><TableCell><span className="flex items-center gap-1">{["withdrawal", "refund"].includes(row.type) ? <ArrowUpFromLine className="size-3" /> : <ArrowDownToLine className="size-3" />}{labels[row.type]}</span></TableCell><TableCell>{methods[row.method]}</TableCell><TableCell>{row.reason ?? row.category ?? "—"}</TableCell><TableCell className="text-right font-medium">{["withdrawal", "refund"].includes(row.type) ? "-" : "+"}{money(row.amountCents)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function ActionMessage({ state }: { state: FinanceActionState }) { return state.message ? <p aria-live="polite" className={state.status === "error" ? "text-sm text-destructive sm:col-span-2" : "text-sm text-emerald-700 sm:col-span-2"}>{state.message}</p> : null; }
