"use client";

import { useActionState, useMemo, useState } from "react";
import Link from "next/link";
import { Calculator, CheckCircle2, Download, Percent, PlusCircle } from "lucide-react";

import type { FinanceActionState } from "@/app/app/cash-actions";
import { addCommissionAdjustmentAction, approveCommissionRunAction, calculateCommissionRunAction, createCommissionRuleAction, toggleCommissionRuleAction } from "@/app/app/commission-actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { getCommissionData } from "@/lib/commerce-data";

type Data = Awaited<ReturnType<typeof getCommissionData>>;
const initial: FinanceActionState = { status: "idle" };

export function CommissionDashboard({ companyId, currency, data }: { companyId: string; currency: string; data: Data }) {
  const [selectedRunId, setSelectedRunId] = useState(data.runs[0]?.id ?? "");
  const [ruleState, ruleAction, rulePending] = useActionState(createCommissionRuleAction, initial);
  const [toggleState, toggleAction, togglePending] = useActionState(toggleCommissionRuleAction, initial);
  const [runState, runAction, runPending] = useActionState(calculateCommissionRunAction, initial);
  const [adjustState, adjustAction, adjustPending] = useActionState(addCommissionAdjustmentAction, initial);
  const [approveState, approveAction, approvePending] = useActionState(approveCommissionRunAction, initial);
  const selectedRun = data.runs.find((run) => run.id === selectedRunId);
  const employeeSummary = useMemo(() => {
    const rows = new Map<string, { employeeId: string; name: string; baseCents: number; commissionCents: number; adjustmentsCents: number }>();
    for (const entry of data.entries.filter((row) => row.runId === selectedRunId)) { const value = rows.get(entry.employeeId) ?? { employeeId: entry.employeeId, name: entry.employeeName, baseCents: 0, commissionCents: 0, adjustmentsCents: 0 }; value.baseCents += entry.baseCents; value.commissionCents += entry.commissionCents; rows.set(entry.employeeId, value); }
    for (const adjustment of data.adjustments.filter((row) => row.runId === selectedRunId)) { const value = rows.get(adjustment.employeeId) ?? { employeeId: adjustment.employeeId, name: adjustment.employeeName, baseCents: 0, commissionCents: 0, adjustmentsCents: 0 }; value.adjustmentsCents += adjustment.amountCents; rows.set(adjustment.employeeId, value); }
    return [...rows.values()].sort((a, b) => b.commissionCents + b.adjustmentsCents - a.commissionCents - a.adjustmentsCents);
  }, [data.adjustments, data.entries, selectedRunId]);
  const money = (cents: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency }).format(cents / 100);
  const today = new Date().toISOString().slice(0, 10);
  const monthStart = `${today.slice(0, 8)}01`;
  return <div className="space-y-6">
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Percent className="size-5" />Nueva regla</CardTitle><CardDescription>La regla más específica tiene prioridad; después se usa el número de prioridad.</CardDescription></CardHeader><CardContent><form action={ruleAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="companyId" value={companyId} /><div className="space-y-2 sm:col-span-2"><Label>Nombre</Label><Input name="name" required minLength={2} maxLength={160} placeholder="Ej. 15% servicios premium" /></div><div className="space-y-2"><Label>Empleado</Label><select name="employeeId" className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="">Todos</option>{data.employees.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="space-y-2"><Label>Servicio</Label><select name="serviceId" className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="">Todos</option>{data.services.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="space-y-2"><Label>Categoría</Label><select name="categoryId" className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="">Todas</option>{data.categories.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="space-y-2"><Label>Prioridad</Label><Input name="priority" type="number" defaultValue="0" min="-1000" max="1000" /></div><div className="space-y-2"><Label>Porcentaje</Label><Input name="ratePercent" type="number" defaultValue="0" min="0" max="100" step="0.01" /></div><div className="space-y-2"><Label>Fijo por unidad</Label><Input name="fixedAmount" type="number" defaultValue="0" min="0" step="0.01" /></div><Message state={ruleState} /><Button disabled={rulePending} className="sm:col-span-2"><PlusCircle />{rulePending ? "Creando…" : "Crear regla"}</Button></form></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Calculator className="size-5" />Calcular periodo</CardTitle><CardDescription>Solo considera ventas completadas; las canceladas quedan excluidas.</CardDescription></CardHeader><CardContent><form action={runAction} className="space-y-4"><input type="hidden" name="companyId" value={companyId} /><div className="space-y-2"><Label>Sucursal</Label><select name="branchId" className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="">Todas</option>{data.branches.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Desde</Label><Input name="from" type="date" defaultValue={monthStart} required /></div><div className="space-y-2"><Label>Hasta</Label><Input name="to" type="date" defaultValue={today} required /></div></div><Message state={runState} /><Button disabled={runPending} className="w-full">{runPending ? "Calculando…" : "Generar cálculo"}</Button></form></CardContent></Card></div>
    <Card><CardHeader><CardTitle>Reglas configuradas</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Regla</TableHead><TableHead>Aplica a</TableHead><TableHead className="text-right">Porcentaje</TableHead><TableHead className="text-right">Fijo</TableHead><TableHead>Estado</TableHead><TableHead /></TableRow></TableHeader><TableBody>{data.rules.map((rule) => <TableRow key={rule.id}><TableCell className="font-medium">{rule.name}<span className="block text-xs text-muted-foreground">Prioridad {rule.priority}</span></TableCell><TableCell>{[rule.employeeName, rule.serviceName, rule.categoryName].filter(Boolean).join(" · ") || "Todas las partidas"}</TableCell><TableCell className="text-right">{rule.rateBasisPoints / 100}%</TableCell><TableCell className="text-right">{money(rule.fixedCents)}</TableCell><TableCell><Badge variant={rule.status === "active" ? "secondary" : "outline"}>{rule.status === "active" ? "Activa" : "Inactiva"}</Badge></TableCell><TableCell><form action={toggleAction}><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="ruleId" value={rule.id} /><Button size="sm" variant="ghost" disabled={togglePending}>{rule.status === "active" ? "Desactivar" : "Activar"}</Button></form></TableCell></TableRow>)}</TableBody></Table><Message state={toggleState} />{data.rules.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">Crea una regla antes de calcular comisiones.</p> : null}</CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>Cálculos</CardTitle></CardHeader><CardContent className="space-y-2">{data.runs.map((run) => <button key={run.id} type="button" onClick={() => setSelectedRunId(run.id)} className={`w-full rounded-lg border p-3 text-left transition ${selectedRunId === run.id ? "border-primary bg-primary/5" : "hover:bg-muted"}`}><div className="flex justify-between gap-2"><span className="font-medium">{run.periodFrom} — {run.periodTo}</span><Badge variant={run.status === "approved" ? "secondary" : "outline"}>{run.status === "approved" ? "Aprobado" : "Borrador"}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{run.branchName ?? "Todas las sucursales"}</p><p className="mt-2 font-semibold">{money(run.totalCents)}</p></button>)}{data.runs.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">Sin cálculos.</p> : null}</CardContent></Card>
    <Card><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>Detalle por empleado</CardTitle><CardDescription>{selectedRun ? `${selectedRun.periodFrom} al ${selectedRun.periodTo}` : "Selecciona un cálculo"}</CardDescription></div>{selectedRun ? <Button variant="outline" size="sm" asChild><Link href={`/api/commissions/${selectedRun.id}.csv`}><Download />CSV</Link></Button> : null}</div></CardHeader><CardContent className="space-y-5">{selectedRun ? <><Table><TableHeader><TableRow><TableHead>Empleado</TableHead><TableHead className="text-right">Base</TableHead><TableHead className="text-right">Comisión</TableHead><TableHead className="text-right">Ajustes</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{employeeSummary.map((row) => <TableRow key={row.employeeId}><TableCell className="font-medium">{row.name}</TableCell><TableCell className="text-right">{money(row.baseCents)}</TableCell><TableCell className="text-right">{money(row.commissionCents)}</TableCell><TableCell className="text-right">{money(row.adjustmentsCents)}</TableCell><TableCell className="text-right font-semibold">{money(row.commissionCents + row.adjustmentsCents)}</TableCell></TableRow>)}</TableBody></Table>{selectedRun.status === "draft" ? <div className="grid gap-4 border-t pt-4 lg:grid-cols-2"><form action={adjustAction} className="space-y-3"><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="runId" value={selectedRun.id} /><Label>Ajuste autorizado</Label><select name="employeeId" required className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="">Empleado</option>{data.employees.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><Input name="amount" type="number" step="0.01" required placeholder="Positivo o negativo" /><Input name="reason" minLength={3} maxLength={1000} required placeholder="Motivo" /><Message state={adjustState} /><Button variant="outline" disabled={adjustPending}>{adjustPending ? "Registrando…" : "Agregar ajuste"}</Button></form><form action={approveAction} className="space-y-3 rounded-lg bg-emerald-50 p-4"><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="runId" value={selectedRun.id} /><p className="font-medium text-emerald-900">Aprobar cálculo</p><p className="text-sm text-emerald-800">Después de aprobar ya no se podrán agregar ajustes.</p><Message state={approveState} /><Button disabled={approvePending}><CheckCircle2 />{approvePending ? "Aprobando…" : "Aprobar"}</Button></form></div> : <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Cálculo aprobado y cerrado para ajustes.</p>}</> : <p className="py-12 text-center text-sm text-muted-foreground">No hay un cálculo seleccionado.</p>}</CardContent></Card></div>
  </div>;
}

function Message({ state }: { state: FinanceActionState }) { return state.message ? <p aria-live="polite" className={state.status === "error" ? "text-sm text-destructive sm:col-span-2" : "text-sm text-emerald-700 sm:col-span-2"}>{state.message}</p> : null; }
