import Link from "next/link";
import { and, asc, desc, eq } from "drizzle-orm";
import { ArrowLeft } from "lucide-react";
import { notFound } from "next/navigation";

import { EmployeeForm } from "@/components/employee-form";
import { EmployeeExceptionForm } from "@/components/employee-exception-form";
import { EmployeeScheduleForm } from "@/components/employee-schedule-form";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getDb } from "@/db";
import { branches, companies, employeeBranches, employeeServices, employees, scheduleExceptions, services, weeklySchedules } from "@/db/schema";

export async function EmployeeDetail({ employeeId, companyId, backHref, canManage }: { employeeId: string; companyId?: string; backHref: string; canManage: boolean }) {
  const db = getDb();
  const [employee] = await db.select().from(employees).where(companyId ? and(eq(employees.id, employeeId), eq(employees.companyId, companyId)) : eq(employees.id, employeeId)).limit(1);
  if (!employee) notFound();
  const [branchRows, serviceRows, assignedBranches, assignedServices, scheduleRows, exceptionRows] = await Promise.all([
    db.select({ id: branches.id, companyId: branches.companyId, name: branches.name }).from(branches).where(and(eq(branches.companyId, employee.companyId), eq(branches.status, "active"))).orderBy(asc(branches.name)),
    db.select({ id: services.id, companyId: services.companyId, name: services.name }).from(services).where(and(eq(services.companyId, employee.companyId), eq(services.status, "active"))).orderBy(asc(services.name)),
    db.select({ id: branches.id, name: branches.name }).from(employeeBranches).innerJoin(branches, and(eq(branches.id, employeeBranches.branchId), eq(branches.companyId, employee.companyId))).where(and(eq(employeeBranches.companyId, employee.companyId), eq(employeeBranches.employeeId, employee.id))).orderBy(asc(branches.name)),
    db.select({ id: employeeServices.serviceId }).from(employeeServices).where(and(eq(employeeServices.companyId, employee.companyId), eq(employeeServices.employeeId, employee.id))),
    db.select({ branchId: weeklySchedules.branchId, dayOfWeek: weeklySchedules.dayOfWeek, startMinute: weeklySchedules.startMinute, endMinute: weeklySchedules.endMinute }).from(weeklySchedules).where(and(eq(weeklySchedules.companyId, employee.companyId), eq(weeklySchedules.employeeId, employee.id), eq(weeklySchedules.scope, "employee"))).orderBy(asc(weeklySchedules.dayOfWeek)),
    db.select({ id: scheduleExceptions.id, type: scheduleExceptions.type, startsAt: scheduleExceptions.startsAt, endsAt: scheduleExceptions.endsAt, reason: scheduleExceptions.reason, branchName: branches.name, timezone: branches.timezone, companyTimezone: companies.timezone }).from(scheduleExceptions).innerJoin(branches, and(eq(branches.id, scheduleExceptions.branchId), eq(branches.companyId, employee.companyId))).innerJoin(companies, eq(companies.id, employee.companyId)).where(and(eq(scheduleExceptions.companyId, employee.companyId), eq(scheduleExceptions.employeeId, employee.id))).orderBy(desc(scheduleExceptions.startsAt)).limit(20),
  ]);
  return <div className="p-4 sm:p-6 lg:p-8"><header className="mb-7"><Button variant="ghost" size="sm" asChild className="-ml-3"><Link href={backHref}><ArrowLeft />Volver</Link></Button><h1 className="mt-3 text-3xl font-semibold tracking-tight">{employee.name}</h1><p className="mt-2 text-sm text-muted-foreground">Configura su perfil, asignaciones y disponibilidad semanal.</p></header>{canManage ? <div className="grid items-start gap-6 2xl:grid-cols-2"><EmployeeForm companies={[]} branches={branchRows} services={serviceRows} fixedCompanyId={employee.companyId} employee={{ id: employee.id, companyId: employee.companyId, name: employee.name, email: employee.email, phone: employee.phone, color: employee.color, status: employee.status, branchIds: assignedBranches.map((branch) => branch.id), serviceIds: assignedServices.map((service) => service.id) }} /><EmployeeScheduleForm companyId={employee.companyId} employeeId={employee.id} branches={assignedBranches} schedules={scheduleRows} /><EmployeeExceptionForm companyId={employee.companyId} employeeId={employee.id} branches={assignedBranches} /><Card><CardHeader><CardTitle>Bloqueos recientes</CardTitle><CardDescription>Últimos periodos no disponibles registrados.</CardDescription></CardHeader><CardContent className="space-y-2">{exceptionRows.map((exception) => { const timezone = exception.timezone ?? exception.companyTimezone; return <div key={exception.id} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">{exception.branchName} · {exception.type === "absence" ? "Ausencia" : exception.type === "break" ? "Descanso" : "Bloqueo"}</p><span className="text-xs text-muted-foreground">{new Intl.DateTimeFormat("es-MX", { timeZone: timezone, dateStyle: "medium" }).format(exception.startsAt)}</span></div><p className="mt-1 text-xs text-muted-foreground">{new Intl.DateTimeFormat("es-MX", { timeZone: timezone, timeStyle: "short" }).format(exception.startsAt)}–{new Intl.DateTimeFormat("es-MX", { timeZone: timezone, timeStyle: "short" }).format(exception.endsAt)}{exception.reason ? ` · ${exception.reason}` : ""}</p></div>; })}{!exceptionRows.length ? <p className="text-sm text-muted-foreground">No hay bloqueos registrados.</p> : null}</CardContent></Card></div> : <p className="rounded-xl border bg-white p-6 text-sm text-muted-foreground">No tienes permisos para modificar este empleado.</p>}</div>;
}
