"use client";

import { useActionState, useMemo, useState } from "react";
import { CreditCard, History, Plus, SlidersHorizontal, XCircle } from "lucide-react";

import type { FinanceActionState } from "@/app/app/cash-actions";
import { adjustGiftCardAction, cancelGiftCardAction, issueGiftCardAction } from "@/app/app/gift-card-actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import type { getGiftCardData } from "@/lib/commerce-data";

type Data = Awaited<ReturnType<typeof getGiftCardData>>;
const initial: FinanceActionState = { status: "idle" };
const movementLabels = { issue: "Emisión", redeem: "Cargo", refund: "Devolución", adjustment: "Ajuste", cancel: "Cancelación" } as const;

export function GiftCardDashboard({ companyId, currency, data }: { companyId: string; currency: string; data: Data }) {
  const [selectedId, setSelectedId] = useState(data.cards[0]?.id ?? "");
  const [issueState, issueAction, issuing] = useActionState(issueGiftCardAction, initial);
  const [adjustState, adjustAction, adjusting] = useActionState(adjustGiftCardAction, initial);
  const [cancelState, cancelAction, cancelling] = useActionState(cancelGiftCardAction, initial);
  const selected = data.cards.find((card) => card.id === selectedId);
  const movements = useMemo(() => data.movements.filter((row) => row.giftCardId === selectedId), [data.movements, selectedId]);
  const money = (cents: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency }).format(cents / 100);
  return <div className="space-y-6">
    <div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-5" />Emitir gift card</CardTitle><CardDescription>El código puede capturarse o generarse automáticamente.</CardDescription></CardHeader><CardContent><form action={issueAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="companyId" value={companyId} /><div className="space-y-2"><Label>Código opcional</Label><Input name="code" maxLength={40} placeholder="Se genera si lo dejas vacío" /></div><div className="space-y-2"><Label>Saldo inicial</Label><Input name="balance" type="number" min="0.01" step="0.01" required /></div><div className="space-y-2"><Label>Cliente</Label><select name="customerId" className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="">Sin cliente</option>{data.customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></div><div className="space-y-2"><Label>Vencimiento</Label><Input name="expiresOn" type="date" /></div><div className="space-y-2 sm:col-span-2"><Label>Notas</Label><Textarea name="notes" maxLength={1000} /></div><Message state={issueState} /><Button disabled={issuing} className="sm:col-span-2"><CreditCard />{issuing ? "Emitiendo…" : "Emitir gift card"}</Button></form></CardContent></Card>
    <Card><CardHeader><CardTitle>Administrar saldo</CardTitle><CardDescription>Los ajustes y cancelaciones quedan en historial inalterable.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="space-y-2"><Label>Gift card</Label><select value={selectedId} onChange={(event) => setSelectedId(event.target.value)} className="h-9 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="">Selecciona</option>{data.cards.map((card) => <option key={card.id} value={card.id}>{card.code} · {money(card.balanceCents)}</option>)}</select></div>{selected ? <><div className="rounded-lg bg-muted p-4"><p className="text-sm text-muted-foreground">Saldo disponible</p><p className="mt-1 text-2xl font-semibold">{money(selected.balanceCents)}</p><p className="mt-1 text-xs text-muted-foreground">{selected.customerName ?? "Sin cliente"} · {selected.status}</p></div><form action={adjustAction} className="space-y-3"><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="giftCardId" value={selected.id} /><Label>Ajuste de saldo</Label><Input name="amount" type="number" step="0.01" required placeholder="Positivo para abono, negativo para cargo" /><Input name="reason" minLength={3} maxLength={1000} required placeholder="Motivo obligatorio" /><Message state={adjustState} /><Button disabled={adjusting || selected.status === "cancelled"} variant="outline"><SlidersHorizontal />{adjusting ? "Ajustando…" : "Registrar ajuste"}</Button></form><form action={cancelAction} className="space-y-3 border-t pt-4"><input type="hidden" name="companyId" value={companyId} /><input type="hidden" name="giftCardId" value={selected.id} /><Input name="reason" minLength={3} maxLength={1000} required placeholder="Motivo de cancelación" /><Message state={cancelState} /><Button disabled={cancelling || selected.status === "cancelled"} variant="destructive"><XCircle />{cancelling ? "Cancelando…" : "Cancelar gift card"}</Button></form></> : <p className="py-8 text-center text-sm text-muted-foreground">Aún no hay gift cards.</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Gift cards</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Código</TableHead><TableHead>Cliente</TableHead><TableHead>Vencimiento</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Inicial</TableHead><TableHead className="text-right">Saldo</TableHead><TableHead><span className="sr-only">Acciones</span></TableHead></TableRow></TableHeader><TableBody>{data.cards.map((card) => <TableRow key={card.id} data-state={selectedId === card.id ? "selected" : undefined}><TableCell className="font-medium">{card.code}</TableCell><TableCell>{card.customerName ?? "—"}</TableCell><TableCell>{card.expiresOn ?? "Sin vencimiento"}</TableCell><TableCell><Badge variant={card.status === "active" ? "secondary" : "outline"}>{card.status}</Badge></TableCell><TableCell className="text-right">{money(card.initialBalanceCents)}</TableCell><TableCell className="text-right font-semibold">{money(card.balanceCents)}</TableCell><TableCell><Button type="button" size="sm" variant="ghost" onClick={() => setSelectedId(card.id)} aria-label={`Administrar gift card ${card.code}`}>Administrar</Button></TableCell></TableRow>)}</TableBody></Table>{data.cards.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No se han emitido gift cards.</p> : null}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><History className="size-5" />Historial {selected ? `· ${selected.code}` : ""}</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Movimiento</TableHead><TableHead>Notas</TableHead><TableHead className="text-right">Importe</TableHead><TableHead className="text-right">Saldo</TableHead></TableRow></TableHeader><TableBody>{movements.map((row) => <TableRow key={row.id}><TableCell>{new Intl.DateTimeFormat("es-MX", { dateStyle: "short", timeStyle: "short" }).format(row.occurredAt)}</TableCell><TableCell>{movementLabels[row.type]}</TableCell><TableCell>{row.notes ?? "—"}</TableCell><TableCell className="text-right">{row.amountCents > 0 ? "+" : ""}{money(row.amountCents)}</TableCell><TableCell className="text-right font-medium">{money(row.balanceAfterCents)}</TableCell></TableRow>)}</TableBody></Table>{selected && movements.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">Sin movimientos.</p> : null}</CardContent></Card>
  </div>;
}

function Message({ state }: { state: FinanceActionState }) { return state.message ? <p aria-live="polite" className={state.status === "error" ? "text-sm text-destructive sm:col-span-2" : "text-sm text-emerald-700 sm:col-span-2"}>{state.message}</p> : null; }
