import Link from "next/link";
import { CalendarCheck, Clock3, Download, FileText, ReceiptText, WalletCards } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { getReportData } from "@/lib/report-data";

type Report = Awaited<ReturnType<typeof getReportData>>;

export function ReportsDashboard({ report, branches, exportParams }: { report: Report; branches: { id: string; name: string }[]; exportParams: string }) {
  const money = (cents: number) => report.mixedCurrencies ? `${new Intl.NumberFormat("es-MX", { minimumFractionDigits: 2 }).format(cents / 100)} (monedas mixtas)` : new Intl.NumberFormat("es-MX", { style: "currency", currency: report.currency }).format(cents / 100);
  const statusLabels: Record<string, string> = { pending: "Pendientes", confirmed: "Confirmadas", waiting: "En espera", in_service: "En servicio", completed: "Completadas", cancelled: "Canceladas", no_show: "No asistió" };
  const maxService = Math.max(...report.topServices.map((row) => row.totalCents), 1);
  return <div className="space-y-6">
    <Card><CardContent><form className="grid gap-3 md:grid-cols-[1fr_1fr_1.5fr_auto_auto]"><input className="h-9 rounded-lg border border-input bg-white px-3 text-sm" type="date" name="from" defaultValue={report.filters.from} aria-label="Desde" /><input className="h-9 rounded-lg border border-input bg-white px-3 text-sm" type="date" name="to" defaultValue={report.filters.to} aria-label="Hasta" /><select className="h-9 rounded-lg border border-input bg-white px-3 text-sm" name="branchId" defaultValue={report.filters.branchId ?? ""}><option value="">Todas las sucursales</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select>{report.filters.companyId ? <input type="hidden" name="companyId" value={report.filters.companyId} /> : null}<Button type="submit">Aplicar</Button><Button variant="outline" asChild><Link href="?">Limpiar</Link></Button></form></CardContent></Card>
    <div className="flex flex-wrap justify-end gap-2"><Button variant="outline" asChild><Link href={`/api/reports/sales.csv?${exportParams}`}><Download />Exportar CSV</Link></Button><Button variant="outline" asChild><Link href={`/api/reports/summary.pdf?${exportParams}`} target="_blank"><FileText />Exportar PDF</Link></Button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      { label: "Ventas netas", value: money(report.totals.revenueCents), detail: `${report.totals.sales} ventas`, icon: WalletCards },
      { label: "Ticket promedio", value: money(report.totals.averageTicketCents), detail: `${report.totals.cancelledSales} canceladas`, icon: ReceiptText },
      { label: "Citas", value: String(report.totals.appointments), detail: `${report.totals.attendedAppointments} atendidas`, icon: CalendarCheck },
      { label: "Ocupación de agenda", value: `${report.totals.occupancyPercent}%`, detail: `${Math.round(report.totals.appointmentMinutes / 6) / 10} de ${Math.round(report.totals.capacityMinutes / 6) / 10} h disponibles`, icon: Clock3 },
    ].map(({ label, value, detail, icon: Icon }) => <Card key={label}><CardContent><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><div className="rounded-lg bg-violet-50 p-2 text-violet-700"><Icon className="size-5" /></div></div></CardContent></Card>)}</div>
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Servicios con más ingresos</CardTitle><CardDescription>Importe neto registrado por partidas.</CardDescription></CardHeader><CardContent className="space-y-4">{report.topServices.map((row) => <div key={row.name}><div className="mb-1 flex justify-between gap-4 text-sm"><span className="truncate font-medium">{row.name} <span className="font-normal text-muted-foreground">× {row.quantity}</span></span><span>{money(row.totalCents)}</span></div><div className="h-2 rounded-full bg-stone-100"><div className="h-2 rounded-full bg-violet-500" style={{ width: `${Math.max(3, row.totalCents / maxService * 100)}%` }} /></div></div>)}{report.topServices.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">Sin ventas en el periodo.</p> : null}</CardContent></Card>
    <Card><CardHeader><CardTitle>Citas por estado</CardTitle><CardDescription>Distribución operativa del periodo.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{Object.entries(report.appointmentStatuses).map(([status, count]) => <div key={status} className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span>{statusLabels[status]}</span><strong>{count}</strong></div>)}</CardContent></Card></div>
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Empleados</CardTitle><CardDescription>Servicios e ingresos atribuidos por partida.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Empleado</TableHead><TableHead className="text-right">Servicios</TableHead><TableHead className="text-right">Ingresos</TableHead></TableRow></TableHeader><TableBody>{report.topEmployees.map((row) => <TableRow key={row.name}><TableCell className="font-medium">{row.name}</TableCell><TableCell className="text-right">{row.quantity}</TableCell><TableCell className="text-right">{money(row.totalCents)}</TableCell></TableRow>)}</TableBody></Table>{report.topEmployees.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">Sin datos.</p> : null}</CardContent></Card>
    <Card><CardHeader><CardTitle>Sucursales</CardTitle><CardDescription>Ventas netas por ubicación.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Sucursal</TableHead><TableHead className="text-right">Ventas</TableHead><TableHead className="text-right">Ingresos</TableHead></TableRow></TableHeader><TableBody>{report.branches.map((row) => <TableRow key={`${row.companyName}-${row.name}`}><TableCell className="font-medium">{row.companyName} · {row.name}</TableCell><TableCell className="text-right">{row.sales}</TableCell><TableCell className="text-right">{money(row.totalCents)}</TableCell></TableRow>)}</TableBody></Table>{report.branches.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">Sin datos.</p> : null}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Formas de pago</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">Efectivo</p><p className="mt-1 text-lg font-semibold">{money(report.paymentMethods.cash)}</p></div><div className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">Tarjeta</p><p className="mt-1 text-lg font-semibold">{money(report.paymentMethods.card)}</p></div><div className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">Transferencia</p><p className="mt-1 text-lg font-semibold">{money(report.paymentMethods.transfer)}</p></div></CardContent></Card>
  </div>;
}
