import type { Metadata } from "next";
import Link from "next/link";
import { and, asc, eq } from "drizzle-orm";
import { ChevronRight } from "lucide-react";
import { AdminPageHeader } from "@/components/admin-page-header";
import { ServiceCategoryForm } from "@/components/service-category-form";
import { ServiceForm } from "@/components/service-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getDb } from "@/db";
import { companies, serviceCategories, services } from "@/db/schema";
export const metadata: Metadata = { title: "Servicios | Superadministración" };
export default async function AdminServicesPage() { const db = getDb(); const [companyRows, categories, rows] = await Promise.all([db.select({ id: companies.id, name: companies.name }).from(companies).where(eq(companies.status, "active")).orderBy(asc(companies.name)), db.select({ id: serviceCategories.id, companyId: serviceCategories.companyId, name: serviceCategories.name, status: serviceCategories.status }).from(serviceCategories).orderBy(asc(serviceCategories.name)), db.select({ id: services.id, code: services.code, name: services.name, durationMinutes: services.durationMinutes, priceCents: services.priceCents, currency: services.currency, status: services.status, categoryName: serviceCategories.name, companyName: companies.name }).from(services).innerJoin(companies, eq(companies.id, services.companyId)).leftJoin(serviceCategories, and(eq(serviceCategories.id, services.categoryId), eq(serviceCategories.companyId, services.companyId))).orderBy(asc(companies.name), asc(services.name))]); return <main className="mx-auto max-w-[1600px] px-5 py-8 sm:px-8"><AdminPageHeader eyebrow="Catálogo global" title="Servicios" description="Administra servicios y categorías de todas las empresas." /><div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_390px]"><Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Servicio</TableHead><TableHead>Empresa</TableHead><TableHead>Categoría</TableHead><TableHead>Duración</TableHead><TableHead>Precio</TableHead><TableHead>Estado</TableHead><TableHead className="w-16" /></TableRow></TableHeader><TableBody>{rows.map((service) => <TableRow key={service.id}><TableCell><p className="font-medium">{service.name}</p><p className="text-xs text-muted-foreground">{service.code}</p></TableCell><TableCell>{service.companyName}</TableCell><TableCell>{service.categoryName ?? "Sin categoría"}</TableCell><TableCell>{service.durationMinutes} min</TableCell><TableCell>{new Intl.NumberFormat("es-MX", { style: "currency", currency: service.currency }).format(service.priceCents / 100)}</TableCell><TableCell><Badge variant={service.status === "active" ? "secondary" : "outline"}>{service.status === "active" ? "Activo" : "Inactivo"}</Badge></TableCell><TableCell><Button variant="ghost" size="icon-sm" asChild><Link href={`/app/admin/servicios/${service.id}`} aria-label={`Editar ${service.name}`}><ChevronRight /></Link></Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card><div className="space-y-6"><ServiceForm companies={companyRows} categories={categories} /><ServiceCategoryForm companies={companyRows} categories={categories} /></div></div></main>; }
